import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,mkdtempSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {spawn} from 'node:child_process';
import {createServer} from 'node:net';
import {setTimeout as delay} from 'node:timers/promises';
const repo=new URL('../',import.meta.url);
const app=readFileSync(new URL('app.js',repo),'utf8');
const html=readFileSync(new URL('index.html',repo),'utf8');
const start=app.indexOf('// 発注書画像取込（固定座標');
const end=app.indexOf('// 📥 旧AI取り込みモード',start);
assert.ok(start>=0&&end>start);
const modalStart=html.indexOf('<!-- 発注書画像取込');
const modalEnd=html.indexOf('<!-- Import Modal',modalStart);
assert.ok(modalStart>=0&&modalEnd>modalStart);
const helper=readFileSync(new URL('sheet-ocr.js',repo),'utf8');
const css=readFileSync(new URL('style.css',repo),'utf8').replace(/@import[^;]+;/g,'');
const harness=String.raw`
const CONFIG={API_URL:'https://mock.invalid',DEALER:'default'};
const ENABLE_SHEET_IMAGE_IMPORT=true; let isMasterSession=true;
const sheetImageImportBtn=document.getElementById('sheet-image-import-btn');
window.onerror=(message)=>{document.body.dataset.result='FAIL';document.getElementById('results').textContent=String(message)};
let sessionToken='UT-token',currentClientName='UT-20260906-ocr-speed-salon';
let currentCart={a:{qty:2,name:'UT 商品A'}};
const itemsData=[{code:'a',name:'UT 商品A'},{code:'b',name:'UT 商品B'},{code:'c',name:'UT 商品C'}];
const updateFromCart=(code,name,qty)=>{currentCart[code]={name,qty}};
const openCartSidebar=()=>{};
const pending=[];
window.fetch=(url,options)=>new Promise((resolve,reject)=>pending.push({body:JSON.parse(options.body),resolve,reject,signal:options.signal}));
const reply=(request,data)=>request.resolve({ok:true,json:async()=>({status:'success',data})});
const tick=()=>new Promise(r=>setTimeout(r,0));
const check=(condition,label)=>{if(!condition)throw Error(label);results.push(label)};
const results=[];
`;
const checks=String.raw`
(async()=>{try {
 await openSheetOcrModal();
 check(!sheetOcrPhotoBtn.disabled&&!sheetOcrCameraBtn.disabled,'D-1 photo enabled while status pending');
 const first=pending.shift();closeSheetOcrModal();await openSheetOcrModal();const second=pending.shift();
 check(first.signal.aborted,'D-2 close aborts request');
 reply(second,{gemini_configured:true});await tick();reply(first,{gemini_configured:false});await tick();
 check(!sheetOcrPhotoBtn.disabled&&sheetOcrStatus.classList.contains('hidden'),'D-2 stale response cannot overwrite reopened modal');
 const request=callSheetOcrApi({action:'get_order_sheet_layout',sheetId:'SO-test1234567890'});
 const stale=pending.shift();currentClientName='other';reply(stale,{});
 let rejected=false;try{await request}catch{rejected=true};check(rejected,'D-2 salon change rejects old response');
 closeSheetOcrModal();currentClientName='UT-20260906-ocr-speed-salon';await openSheetOcrModal();reply(pending.shift(),{gemini_configured:true});await tick();
 const products=itemsData.map((item,i)=>({cell_id:'c'+i,product_code:item.code,row_bbox:[0,i*3000,10000,2000],qty_bbox:[8000,i*3000,1000,2000]}));
 const cells=[{cell_id:'c0',mark_type:'arabic_digit',quantity:3,raw_reading:'3',confidence:'high'},
 {cell_id:'c1',mark_type:'blank',quantity:null,raw_reading:'',confidence:'high'},
 {cell_id:'c2',mark_type:'unclear',quantity:null,raw_reading:'?',confidence:'low'}];
 sheetOcrState.reviewRows=sheetOcr.buildReviewRows(products,cells,itemsData,true);
 sheetOcrState.rectifiedCanvas=document.createElement('canvas');sheetOcrState.rectifiedCanvas.width=400;sheetOcrState.rectifiedCanvas.height=600;
 const ctx=sheetOcrState.rectifiedCanvas.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,400,600);ctx.fillStyle='black';ctx.font='24px sans-serif';ctx.fillText('UT sample 3',10,40);
 sheetOcrState.fingerprint='UT-image';sheetOcrState.reviewStartedAt=performance.now();
 sheetOcrUploadStep.classList.add('hidden');sheetOcrReviewStep.classList.remove('hidden');renderSheetOcrReview();
 check(sheetOcrReviewList.children.length===2,'D-3 blanks omitted from initial render');
 check(sheetOcrCartBtn.disabled,'D-5 unclear blocks cart');
 document.getElementById('sheet-ocr-show-blank').click();check(sheetOcrReviewList.children.length===3,'D-3 blank accessible');
 const blank=document.getElementById('sheet-ocr-qty-1');blank.value='4';blank.dispatchEvent(new Event('input'));
 check(sheetOcrState.reviewRows[1].quantity===4,'D-3 false blank can be recovered');
 document.getElementById('sheet-ocr-next-attention').click();check(document.activeElement.id==='sheet-ocr-qty-2','D-3 next attention focus');
 const unclear=document.getElementById('sheet-ocr-qty-2');unclear.value='1.5';unclear.dispatchEvent(new Event('input'));
 check(sheetOcrCartBtn.disabled,'D-5 fractional quantity blocked');
 unclear.value='0';unclear.dispatchEvent(new Event('input'));
 check(!sheetOcrCartBtn.disabled,'D-3 correction enables cart');
 check(document.getElementById('sheet-ocr-addition-summary').textContent.includes('現在2 ＋ 今回3 ＝ 合計5'),'D-4 addition preview');
 const savedRows=sheetOcrState.reviewRows;const savedCanvas=sheetOcrState.rectifiedCanvas;
 sheetOcrState.sourceCanvas=savedCanvas;sheetOcrState.page={products};sheetOcrState.qr={sheet_id:'SO-test1234567890',page_no:1};
 sheetOcrState.corners=[{x:0,y:0},{x:399,y:0},{x:399,y:599},{x:0,y:599}];
 const failedRead=recognizeSheetOcrPhoto();for(let i=0;i<100&&!pending.length;i++)await tick();
 check(pending.length===1,'D-5 one OCR request per sheet');
 const failedRequest=pending.shift();check(failedRequest.body.responseFormat==='compact-v1','D-5 compact request format');
 reply(failedRequest,{cells:[cells[0]]});await failedRead;
 check(!sheetOcrState.busy&&!sheetOcrCornerStep.classList.contains('hidden')&&currentCart.a.qty===2,'D-5 missing cell rejects and returns to correction');
 const successfulRead=recognizeSheetOcrPhoto();for(let i=0;i<100&&!pending.length;i++)await tick();
 pending.shift().resolve({ok:true,json:async()=>({status:'success',data:{cells},meta:{elapsed_ms:17,server_ms:21,output_tokens:80}})});await successfulRead;
 check(sheetOcrState.timings.gemini_ms===17&&sheetOcrState.timings.to_review_ms>=0&&!sheetOcrReviewStep.classList.contains('hidden'),'D-1 timing metadata and review transition');
 sheetOcrState.reviewRows=savedRows;sheetOcrState.rectifiedCanvas=savedCanvas;renderSheetOcrReview();
 applySheetOcrToCart();check(currentCart.a.qty===5&&currentCart.b.qty===4,'D-4 cart addition');
 await openSheetOcrModal();reply(pending.shift(),{gemini_configured:true});await tick();
 sheetOcrState.reviewRows=savedRows;sheetOcrState.rectifiedCanvas=savedCanvas;sheetOcrState.fingerprint='UT-image';sheetOcrState.reviewStartedAt=performance.now();
 sheetOcrUploadStep.classList.add('hidden');sheetOcrReviewStep.classList.remove('hidden');renderSheetOcrReview();
 applySheetOcrToCart();check(currentCart.a.qty===5,'D-4 same image needs explicit second action');
 const quantity=document.getElementById('sheet-ocr-qty-0');quantity.value='1';quantity.dispatchEvent(new Event('input'));
 applySheetOcrToCart();check(currentCart.a.qty===5,'D-4 changing quantity invalidates duplicate confirmation');
 setSheetOcrStep(4);
 check(sheetOcrModal.getBoundingClientRect().right<=innerWidth&&sheetOcrModal.scrollWidth<=sheetOcrModal.clientWidth,'mobile modal no horizontal overflow');
 document.body.dataset.result='PASS';document.getElementById('results').textContent=JSON.stringify(results);
 }catch(error){document.body.dataset.result='FAIL';document.getElementById('results').textContent=error.stack}})();
`;
const dir=mkdtempSync(join(tmpdir(),'b2b-ocr-ux-'));
const path=join(dir,'fixture.html');
writeFileSync(path,`<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><style>${css}</style><button id="sheet-image-import-btn">画像取込</button>${html.slice(modalStart,modalEnd)}<pre id="results" style="display:none"></pre><script>${helper}</script><script>${harness}${app.slice(start,end)}${checks}</script>`);
const chrome='/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
const portServer=createServer();await new Promise(r=>portServer.listen(0,'127.0.0.1',r));
const port=portServer.address().port;await new Promise(r=>portServer.close(r));
const child=spawn(chrome,['--headless','--no-sandbox','--disable-gpu','--no-first-run','--disable-background-networking',`--user-data-dir=${join(dir,'profile')}`,`--remote-debugging-port=${port}`,'about:blank'],{stdio:'ignore'});
let socket;
try {
 let tabs;
 for(let i=0;i<100;i++){try{tabs=(await (await fetch(`http://127.0.0.1:${port}/json`)).json()).filter(tab=>tab.type==='page');if(tabs.length)break}catch{}await delay(100)}
 assert.ok(tabs?.length,'Chrome CDP startup');
 socket=new WebSocket(tabs[0].webSocketDebuggerUrl);
 await new Promise((resolve,reject)=>{socket.addEventListener('open',resolve,{once:true});socket.addEventListener('error',reject,{once:true})});
 let serial=0;const waiting=new Map();
 socket.addEventListener('message',event=>{const data=JSON.parse(event.data);if(data.id&&waiting.has(data.id)){const {resolve,reject}=waiting.get(data.id);waiting.delete(data.id);data.error?reject(Error(JSON.stringify(data.error))):resolve(data.result)}});
 const cdp=(method,params={})=>new Promise((resolve,reject)=>{const id=++serial;const timer=setTimeout(()=>{waiting.delete(id);reject(Error('CDP timeout: '+method))},10000);waiting.set(id,{resolve:value=>{clearTimeout(timer);resolve(value)},reject:error=>{clearTimeout(timer);reject(error)}});socket.send(JSON.stringify({id,method,params}))});
 await cdp('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
 await cdp('Page.navigate',{url:`file://${path}`});
 let state;
 for(let i=0;i<100;i++){await delay(100);const r=await cdp('Runtime.evaluate',{expression:'JSON.stringify({status:document.body?.dataset.result,results:document.getElementById("results")?.textContent})',returnByValue:true});state=JSON.parse(r.result.value);if(state.status)break}
 const dom=await cdp('Runtime.evaluate',{expression:'document.documentElement.outerHTML',returnByValue:true});writeFileSync(join(dir,'result.html'),dom.result.value);
 await delay(400);
 const shot=await cdp('Page.captureScreenshot',{format:'png'});writeFileSync(join(dir,'mobile.png'),Buffer.from(shot.data,'base64'));
 assert.equal(state.status,'PASS',state.results||'Browser checks timed out');
 await cdp('Emulation.setDeviceMetricsOverride',{width:1280,height:900,deviceScaleFactor:1,mobile:false});
 const desktop=await cdp('Page.captureScreenshot',{format:'png'});writeFileSync(join(dir,'desktop.png'),Buffer.from(desktop.data,'base64'));
 console.log('PASS browser UX: '+state.results);console.log('Artifacts: '+dir);
}finally{if(socket)socket.close();child.kill();}
